# Goal - sent by Pad
string pad_name
uint8 action 

uint8 ACTION_LAND = 0
uint8 ACTION_TAKEOFF = 1
---
# Result -sent by CF
uint8 result
string reason

uint8 RESULT_UNKNOWN = 0
uint8 RESULT_ON_PAD = 1
uint8 RESULT_NOT_ON_PAD = 2
uint8 RESULT_FAILURE = 3
---
# Feedback - sent by CF
uint8 status

uint8 STATUS_LANDING_APPROACH_IDLE = 0
uint8 STATUS_LANDING_APPROACH_CLOSE = 1
uint8 STATUS_LANDING = 2
uint8 STATUS_LANDED = 3

uint8 STATUS_TAKEOFF_IN_PAD = 3
uint8 STATUS_TAKEOFF_LEFT_PAD = 4
uint8 STATUS_TAKEOFF_CLEARED_PAD = 5
geometry_msgs/PoseStamped current_pose