# Goal - sent by CF
string name 
uint8 action

float32 max_wait_time # in seconds, time to wait for right acquisition before giving up
float32 usage_time #  in seconds, expected time to use the right after acquisition 

uint8 ACTION_LAND = 0
uint8 ACTION_TAKEOFF = 1
uint8 ACTION_PLACE_ON = 2
uint8 ACTION_REMOVE = 3
---
# Result - sent by Pad
string reason
bool success # true if canceled by client, false if lock timeouted etc.
---
# Feedback - sent by Pad
uint8 status
float32 time_remaining # in seconds, expected time until acquisition or time left until timeout

geometry_msgs/PoseStamped target_pose # target pose to land on or takeoff from



uint8 STATUS_WAITING_FOR_RIGHT = 0
uint8 STATUS_ACQUIRED_RIGHT = 1