string name 
float32 max_wait_time # in seconds, time to wait for right acquisition before giving up
float32 usage_time #  in seconds, expected time to use the right after acquisition 
---
bool success # true if canceled by client, false if lock timeouted etc.
---
uint8 status
float32 time_remaining # in seconds, expected time until acquisition or time left until timeout


uint8 STATUS_WAITING_FOR_RIGHT = 0
uint8 STATUS_ACQUIRED_RIGHT = 1