/**:
  ros__parameters:
    default_firmware_params:
      commander:
        enHighLevel: 1
      stabilizer:
        estimator: 2
        controller: 1
      posCtlPid:
        thrustBase: 45000 # 36000 #60000 for 250maH was great
      