/**:
  ros__parameters:
    default_firmware_params:
      stabilizer:
        estimator: 2 # 1: complementary, 2: ekf
        controller: 1 # 1: PID, 2: Mellinger
      locSrv:
        extPosStdDev: 1e-3
      ctrlMel:
        mass: 0.0354 # 35.4 g (weighed(350mah batteries))
        kp_z: 1.00 # from 1.25
        ki_z: 0.1 # from 0.05
        kd_z: 0.3 # from 0.4


      