flies:
# ROW A
#- id: 0xA0
#  pad: 0xA0
#  channel: 100
- id: 0xA1
  pad: 0xA1
  channel: 100
- id: 0xA2
  pad: 0xA2
  channel: 100
- id: 0xA3
  pad: 0xA3
  channel: 100
- id: 0xA4
  pad: 0xA4
  channel: 100
- id: 0xA5
  pad: 0xA5
  channel: 100
- id: 0xA6
  pad: 0xA6
  channel: 100
- id: 0xA7
  pad: 0xA7
  channel: 100
#- id: 0xA8
#  pad: 0xA8
#  channel: 100

# ROW B
- id: 0xB0
  pad: 0xB0
  channel: 100
- id: 0xB1
  pad: 0xB1
  channel: 100
- id: 0xB2
  pad: 0xB2
  channel: 100
- id: 0xB3
  pad: 0xB3
  channel: 100
- id: 0xB4
  pad: 0xB4
  channel: 100
- id: 0xB5
  pad: 0xB5
  channel: 100
- id: 0xB6
  pad: 0xB6
  channel: 100
- id: 0xB7
  pad: 0xB7
  channel: 100
- id: 0xB8
  pad: 0xB8
  channel: 100

# ROW C
- id: 0xC0
  pad: 0xC0
  channel: 100
- id: 0xC1
  pad: 0xC1
  channel: 100
- id: 0xC2
  pad: 0xC2
  channel: 100
- id: 0xC3
  pad: 0xC3
  channel: 100
- id: 0xC4
  pad: 0xC4
  channel: 100
- id: 0xC5
  pad: 0xC5
  channel: 100
- id: 0xC6
  pad: 0xC6
  channel: 100
- id: 0xC7
  pad: 0xC7
  channel: 100
- id: 0xC8
  pad: 0xC8
  channel: 100

# ROW D
- id: 0xD0
  pad: 0xD0
  channel: 50
- id: 0xD1
  pad: 0xD1
  channel: 50
- id: 0xD2
  pad: 0xD2
  channel: 50
- id: 0xD3
  pad: 0xD3
  channel: 50
- id: 0xD4
  pad: 0xD4
  channel: 50
- id: 0xD5
  pad: 0xD5
  channel: 50
- id: 0xD6
  pad: 0xD6
  channel: 50
- id: 0xD7
  pad: 0xD7
  channel: 50
- id: 0xD8
  pad: 0xD8
  channel: 50

# ROW E
- id: 0xE0
  pad: 0xE0
  channel: 50
- id: 0xE1
  pad: 0xE1
  channel: 50
- id: 0xE2
  pad: 0xE2
  channel: 50
- id: 0xE3
  pad: 0xE3
  channel: 50
- id: 0xE4
  pad: 0xE4
  channel: 50
- id: 0xE5
  pad: 0xE5
  channel: 50
- id: 0xE6
  pad: 0xE6
  channel: 50
- id: 0xE7
  pad: 0xE7
  channel: 50
- id: 0xE8
  pad: 0xE8
  channel: 50

# ROW F
#- id: 0xF0
#  pad: 0xF0
#  channel: 100
- id: 0xF1
  pad: 0xF1
  channel: 100
- id: 0xF2
  pad: 0xF2
  channel: 100
- id: 0xF3
  pad: 0xF3
  channel: 100
- id: 0xF4
  pad: 0xF4
  channel: 100
- id: 0xF5
  pad: 0xF5
  channel: 100
- id: 0xF6
  pad: 0xF6
  channel: 100
- id: 0xF7
  pad: 0xF7
  channel: 100
#- id: 0xF8
#  pad: 0xF8
#  channel: 100