flies:
- id: 0xA0
  pad: 0xA0
  channel: 100
- id: 0xA1
  pad: 0xA1
  channel: 100
- id: 0xA2
  pad: 0xA2
  channel: 100
- id: 0xA3
  pad: 0xA3
  channel: 100
- id: 0xA4
  pad: 0xA4
  channel: 100
- id: 0xB0
  pad: 0xB0
  channel: 100
- id: 0xB1
  pad: 0xB1
  channel: 100
- id: 0xB2
  pad: 0xB2
  channel: 100
- id: 0xB3
  pad: 0xB3
  channel: 100
- id: 0xB4
  pad: 0xB4
  channel: 100
- id: 0xC0
  pad: 0xC0
  channel: 100
- id: 0xC1
  pad: 0xC1
  channel: 100
- id: 0xC2
  pad: 0xC2
  channel: 100
- id: 0xC3
  pad: 0xC3
  channel: 100
- id: 0xC4
  pad: 0xC4
  channel: 100
- id: 0xD0
  pad: 0xD0
  channel: 100
- id: 0xD1
  pad: 0xD1
  channel: 100
- id: 0xD2
  pad: 0xD2
  channel: 100
- id: 0xD3
  pad: 0xD3
  channel: 100
- id: 0xD4
  pad: 0xD4
  channel: 100
