flies:
- id: 0xA0
  pad: 0xA0
  channel: 100
- id: 0xA1
  pad: 0xA1
  channel: 100
- id: 0xA2
  pad: 0xA2
  channel: 100
- id: 0xA3
  pad: 0xA3
  channel: 100
- id: 0xA4
  pad: 0xA4
  channel: 100
- id: 0xB0
  pad: 0xB0
  channel: 100
