pads:
# ROW A
#- id: 0
#  pos:
#    - 0
#    - 0
- id: 1
  pos: 
    - 0 
    - 1
- id: 2
  pos: 
    - 0 
    - 2
- id: 3
  pos: 
    - 0 
    - 3
- id: 4
  pos: 
    - 0 
    - 4
- id: 5
  pos: 
    - 0 
    - 5
- id: 6
  pos: 
    - 0 
    - 6
- id: 7
  pos: 
    - 0 
    - 7
#- id: 8
#  pos:
#    - 0
#    - 8

# ROW B
- id: 9
  pos:
    - 1
    - 0
- id: 10
  pos:
    - 1
    - 1
- id: 11
  pos:
    - 1
    - 2
- id: 12
  pos:
    - 1
    - 3
- id: 13
  pos:
    - 1
    - 4
- id: 14
  pos:
    - 1
    - 5
- id: 15
  pos:
    - 1
    - 6
- id: 16
  pos:
    - 1
    - 7
- id: 17
  pos:
    - 1
    - 8

# ROW C
- id: 18
  pos:
    - 2
    - 0
- id: 19
  pos:
    - 2
    - 1
- id: 20
  pos:
    - 2
    - 2
- id: 21
  pos:
    - 2
    - 3
- id: 22
  pos:
    - 2
    - 4
- id: 23
  pos:
    - 2
    - 5
- id: 24
  pos:
    - 2
    - 6
- id: 25
  pos:
    - 2
    - 7
- id: 26
  pos:
    - 2
    - 8

# ROW D
- id: 27
  pos:
    - 3
    - 0
- id: 28
  pos:
    - 3
    - 1
- id: 29
  pos:
    - 3
    - 2
- id: 30
  pos:
    - 3
    - 3
- id: 31
  pos:
    - 3
    - 4
- id: 32
  pos:
    - 3
    - 5
- id: 33
  pos:
    - 3
    - 6
- id: 34
  pos:
    - 3
    - 7
- id: 35
  pos:
    - 3
    - 8

# ROW E
- id: 36
  pos:
    - 4
    - 0
- id: 37
  pos:
    - 4
    - 1
- id: 38
  pos:
    - 4
    - 2
- id: 39
  pos:
    - 4
    - 3
- id: 40
  pos:
    - 4
    - 4
- id: 41
  pos:
    - 4
    - 5
- id: 42
  pos:
    - 4
    - 6
- id: 43
  pos:
    - 4
    - 7
- id: 44
  pos:
    - 4
    - 8

# ROW F
#- id: 45
#  pos:
#    - 5
#    - 0
- id: 46
  pos:
    - 5
    - 1
- id: 47
  pos:
    - 5
    - 2
- id: 48
  pos:
    - 5
    - 3
- id: 49
  pos:
    - 5
    - 4
- id: 50
  pos:
    - 5
    - 5
- id: 51
  pos:
    - 5
    - 6
- id: 52
  pos:
    - 5
    - 7
#- id: 53
#  pos:
#    - 5
#    - 8
