flies:
# ROW A
#- id: 0xA0
#  pad: 0
#  channel: 100
- id: 0xA1
  pad: 1
  channel: 100
- id: 0xA2
  pad: 2
  channel: 100
- id: 0xA3
  pad: 3
  channel: 100
- id: 0xA4
  pad: 4
  channel: 100
- id: 0xA5
  pad: 5
  channel: 100
- id: 0xA6
  pad: 6
  channel: 100
- id: 0xA7
  pad: 7
  channel: 100
#- id: 0xA8
#  pad: 8
#  channel: 100

# ROW B
- id: 0xB0
  pad: 9
  channel: 100
- id: 0xB1
  pad: 10
  channel: 100
- id: 0xB2
  pad: 11
  channel: 100
- id: 0xB3
  pad: 12
  channel: 100
- id: 0xB4
  pad: 13
  channel: 100
- id: 0xB5
  pad: 14
  channel: 100
- id: 0xB6
  pad: 15
  channel: 100
- id: 0xB7
  pad: 16
  channel: 100
- id: 0xB8
  pad: 17
  channel: 100

# ROW C
- id: 0xC0
  pad: 18
  channel: 100
- id: 0xC1
  pad: 19
  channel: 100
- id: 0xC2
  pad: 20
  channel: 100
- id: 0xC3
  pad: 21
  channel: 100
- id: 0xC4
  pad: 22
  channel: 100
- id: 0xC5
  pad: 23
  channel: 100
- id: 0xC6
  pad: 24
  channel: 100
- id: 0xC7
  pad: 25
  channel: 100
- id: 0xC8
  pad: 26
  channel: 100

# ROW D
- id: 0xD0
  pad: 27
  channel: 100
- id: 0xD1
  pad: 28
  channel: 100
- id: 0xD2
  pad: 29
  channel: 100
- id: 0xD3
  pad: 30
  channel: 100
- id: 0xD4
  pad: 31
  channel: 100
- id: 0xD5
  pad: 32
  channel: 100
- id: 0xD6
  pad: 33
  channel: 100
- id: 0xD7
  pad: 34
  channel: 100
- id: 0xD8
  pad: 35
  channel: 100

# ROW E
- id: 0xE0
  pad: 36
  channel: 100
- id: 0xE1
  pad: 37
  channel: 100
- id: 0xE2
  pad: 38
  channel: 100
- id: 0xE3
  pad: 39
  channel: 100
- id: 0xE4
  pad: 40
  channel: 100
- id: 0xE5
  pad: 41
  channel: 100
- id: 0xE6
  pad: 42
  channel: 100
- id: 0xE7
  pad: 43
  channel: 100
- id: 0xE8
  pad: 44
  channel: 100

# ROW F
#- id: 0xF0
#  pad: 45
#  channel: 100
- id: 0xF1
  pad: 46
  channel: 100
- id: 0xF2
  pad: 47
  channel: 100
- id: 0xF3
  pad: 48
  channel: 100
- id: 0xF4
  pad: 49
  channel: 100
- id: 0xF5
  pad: 50
  channel: 100
- id: 0xF6
  pad: 51
  channel: 100
- id: 0xF7
  pad: 52
  channel: 100
#- id: 0xF8
#  pad: 53
#  channel: 100