pads:
# ROW A
#- id: 0
#  pos:
#    - 0
#    - 0
- id: 0xA1
  pos: 
    - 0 
    - 1
- id: 0xA2
  pos: 
    - 0 
    - 2
- id: 0xA3
  pos: 
    - 0 
    - 3
- id: 0xA4
  pos: 
    - 0 
    - 4
- id: 0xA5
  pos: 
    - 0 
    - 5
- id: 0xA6
  pos: 
    - 0 
    - 6
- id: 0xA7
  pos: 
    - 0 
    - 7
#- id: 8
#  pos:
#    - 0
#    - 8

# ROW B
- id: 0xB0
  pos:
    - 1
    - 0
- id: 0xB1
  pos:
    - 1
    - 1
- id: 0xB2
  pos:
    - 1
    - 2
- id: 0xB3
  pos:
    - 1
    - 3
- id: 0xB4
  pos:
    - 1
    - 4
- id: 0xB5
  pos:
    - 1
    - 5
- id: 0xB6
  pos:
    - 1
    - 6
- id: 0xB7
  pos:
    - 1
    - 7
- id: 0xB8
  pos:
    - 1
    - 8

# ROW C
- id: 0xC0
  pos:
    - 2
    - 0
- id: 0xC1
  pos:
    - 2
    - 1
- id: 0xC2
  pos:
    - 2
    - 2
- id: 0xC3
  pos:
    - 2
    - 3
- id: 0xC4
  pos:
    - 2
    - 4
- id: 0xC5
  pos:
    - 2
    - 5
- id: 0xC6
  pos:
    - 2
    - 6
- id: 0xC7
  pos:
    - 2
    - 7
- id: 0xC8
  pos:
    - 2
    - 8

# ROW D
- id: 0xD0
  pos:
    - 3
    - 0
- id: 0xD1
  pos:
    - 3
    - 1
- id: 0xD2
  pos:
    - 3
    - 2
- id: 0xD3
  pos:
    - 3
    - 3
- id: 0xD4
  pos:
    - 3
    - 4
- id: 0xD5
  pos:
    - 3
    - 5
- id: 0xD6
  pos:
    - 3
    - 6
- id: 0xD7
  pos:
    - 3
    - 7
- id: 0xD8
  pos:
    - 3
    - 8

# ROW E
- id: 0xE0
  pos:
    - 4
    - 0
- id: 0xE1
  pos:
    - 4
    - 1
- id: 0xE2
  pos:
    - 4
    - 2
- id: 0xE3
  pos:
    - 4
    - 3
- id: 0xE4
  pos:
    - 4
    - 4
- id: 0xE5
  pos:
    - 4
    - 5
- id: 0xE6
  pos:
    - 4
    - 6
- id: 0xE7
  pos:
    - 4
    - 7
- id: 0xE8
  pos:
    - 4
    - 8

# ROW F
#- id: 0xF0
#  pos:
#    - 5
#    - 0
- id: 0xF1
  pos:
    - 5
    - 1
- id: 0xF2
  pos:
    - 5
    - 2
- id: 0xF3
  pos:
    - 5
    - 3
- id: 0xF4
  pos:
    - 5
    - 4
- id: 0xF5
  pos:
    - 5
    - 5
- id: 0xF6
  pos:
    - 5
    - 6
- id: 0xF7
  pos:
    - 5
    - 7
#- id: 0xF8
#  pos:
#    - 5
#    - 8
