/tracker: # name of node
  ros__parameters:
    publishSingleMarkerObjectsToTf: false
    pointCloud2TopicName: "pointCloud2"
    logEnabled: true
    latencyThreshold: 0.035 # seconds
    tfBroadcastRate: 20 # Hz, this also represents broadcast rate
    numMarkerConfigurations: 2
    markerConfigurations:
      "0": # for ISSE
        numPoints: 1
        offset: [ 0.0, 0.0, 0.02 ]
        points:
          "0": [ 0.0, 0.0, 0.0 ]
      "1":  # for Smart Pad
        numPoints: 3
        offset: [0.0, 0.0, 0.0]
        points:
          "0": [0.1, 0.0, 0.0]
          "1": [0.0, 0.1, 0.0]
          "2": [0.0, -0.1, 0.0]
    numDynamicsConfigurations: 2
    dynamicsConfigurations:
      "0":
        maxXVelocity: 1.75 # Only these are relevant for single marker tracking.
        maxYVelocity: 1.75 # Only these are relevant for single marker tracking.
        maxZVelocity: 2.5 # Only these are relevant for single marker tracking. Needs to be higher for dynamic takeoffs.
        maxPitchRate: 20.0
        maxRollRate: 20.0
        maxYawRate: 10.0
        maxRoll: 1.4
        maxPitch: 1.4
        maxFitnessScore: 0.001
      "1": # Smart Pads
        maxXVelocity: 1.75 
        maxYVelocity: 1.75
        maxZVelocity: 2.5
        maxPitchRate: 20.0
        maxRollRate: 20.0
        maxYawRate: 10.0
        maxRoll: 1.4
        maxPitch: 1.4
        maxFitnessScore: 1.0