<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>smart_pad</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="vinzenz@malke.info">vinzenzm</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>pad_management_cpp</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>smart_pad_interfaces</depend>

  <test_depend>crazyflie_simulation_examples</test_depend>
  <test_depend>crazyflie_simulation_gateway</test_depend>
  <test_depend>launch</test_depend>
  <test_depend>launch_ros</test_depend>
  <test_depend>launch_testing</test_depend>
  <test_depend>launch_testing_ament_cmake</test_depend>
  <test_depend>lifecycle_msgs</test_depend>
  <test_depend>pad_management_interfaces</test_depend>
  <test_depend>padflies_cpp</test_depend>
  <test_depend>rclcpp_components</test_depend>
  <test_depend>rclpy</test_depend>
  <test_depend>std_msgs</test_depend>
  <test_depend>std_srvs</test_depend>
  <test_depend>tf2_ros</test_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
