<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>crazyflie_flight_controller_examples</name>
  <version>0.0.0</version>
  <description>Examples and scalability tests for the Crazyflie flight controller.</description>
  <maintainer email="vinzenz@malke.info">winni</maintainer>
  <license>TODO: License declaration</license>

  <exec_depend>collision_avoidance</exec_depend>
  <exec_depend>crazyflie_simulation_examples</exec_depend>
  <exec_depend>crazyflie_simulation_gateway</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>lifecycle_msgs</exec_depend>
  <exec_depend>padflies_cpp</exec_depend>
  <exec_depend>padflies_interfaces</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>simpleflie_behaviors</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
